<?php

namespace fs\crudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * terceroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class terceroRepository extends EntityRepository
{
}
